MNT: Remove assert_array_almost_equal old infs logic, but test fails!
The code for infs masking and comparison in
assert_array_almost_equal.compare appears no longer needed;
since it was added, similar handling was added to assert_array_compare
which runs prior to calling the comparison function.

However, removing the handling in assert_array_almost_equal.compare
triggers a test failure, because assert_array_compare doesn't handle
complex infs:

```
<...>

x = array([ 1.+0.j ,  2.+1.j , inf+0.5j,  4.+0.j ]), y = array([ 1.+0.j ,  2.+1.j , inf+0.5j,  4.+0.j ])

    def compare(x, y):
        # make sure y is an inexact type to avoid abs(MIN_INT); will cause
        # casting of x later.
        dtype = result_type(y, 1.)
        y = np.asanyarray(y, dtype)
>       z = abs(x - y)
E       RuntimeWarning: invalid value encountered in subtract

<...>

numpy/testing/_private/utils.py:1155: RuntimeWarning
================================================================================================================== short test summary info ==================================================================================================================
FAILED numpy/lib/tests/test_function_base.py::TestInterp::test_complex_interp - RuntimeWarning: invalid value encountered in subtract
```

Besides just being a nice cleanup, a specific motivation is towards
reporting max errors indices (#28827). Without this change,
assert_array_almost_equal.compare can produce an output shape different
from its input, requiring additional logic to produce the correct
indices in the original array.