ENH: Ensure dispatcher TypeErrors report original name
This replaces the name in the TypeError with the actually raised
name.  In principle we could add one more check, because a
signature related TypeError must have a traceback with exactly
one entry (so `sys.exc_info()[2].tb_next is None`).
In practice this seems unnecessary though.

This ensures the following message:

    >>> np.histogram(asdf=3)
    TypeError: histogram() got an unexpected keyword argument 'asdf'

Closes gh-21647