BUG: gh-2785, np.unique: TypeError: requested sort not available for type
Revert "BUG: ticket #2063, make unique return consistent index."

This reverts commit 74b9f5eef8fac643bf9012dbb2ac6b4b19f46892.

Conflicts:
	numpy/core/tests/test_regression.py

This commit introduced a regression in `np.unique` for certain data types:

  >>> A = np.array([[1, 2], [1, 3], [1, 2]], dtype='i')
  >>> B, I, J = np.unique(A.view([('', A.dtype)]*A.shape[1]), True, True)
  Traceback (most recent call last):
    File ".../numpy/lib/arraysetops.py", line 178, in unique
      perm = ar.argsort(kind='mergesort')
  TypeError: requested sort not available for type