BUG: fix unique(arr, axis=n) when `0 in arr.shape`
Previously, `unique` failed with two forms of errors if:

- the `axis` argument is used, not `None` (e.g. `axis=0`)
- the input array has a zero in one or more of its dimensions (e.g. `shape=(1, 0, 2)`)

If `axis` is one of the zero dimensions (`arr.shape[axis] == 0`), it failed in the first `reshape`
with:

    ValueError: cannot reshape array of size 0 into shape (0,newaxis)

If `axis` is not one of the zero dimensions (`arr.shape[axis] != 0`), it failed at `consolidated =
ar.view(...)` with:

    ValueError: When changing to a smaller dtype, its size must be a divisor of the size of original
    dtype

This patch special cases empty arrays to skip over all of that reshaping logic, because it isn't
needed: when the array is empty, the result(s) are empty too, and that can be deduced without any
data reshaping or transformations.

Fixes: #15559