DEP: Remove np.pkgload, which was deprecated in 1.10
Attempts to use this on either cpython27 or cpython35, in either a shell or a script, gives:

    NameError: name '__path__' is not defined

Perhaps I'm calling it wrong, but it might just be broken.