BLD: add back stdlib.h include in pcg64.h
This seems to have been removed by accident in #21887
stdlib.h is required for _rotr64() further down.

Fixes:
  error: call to undeclared function '_rotr64'; ISO C99 and later do not support
  implicit function declarations [-Wimplicit-function-declaration]