SIMD, BLD: Fix Highway target attribute build failure on ppc64 (#30392)
On GCC < 13, compiler target attributes cause a build failure with the
`power9/vsx3` feature enabled:
```
from ../numpy/_core/src/umath/loops_trigonometric.dispatch.cpp:5:
hwy/ops/ppc_vsx-inl.h: In function ‘np::simd::{anonymous}::Vec<TLane>
np::simd::{anonymous}::LoadN(const TLane*, size_t) [with TLane =
float]’:
hwy/ops/ppc_vsx-inl.h:1200:19: error: inlining failed in call to
‘always_inline’ ‘hwy::N_PPC10::VFromD<D> 1200 | HWY_API VFromD<D>
LoadN(D d, const T* HWY_RESTRICT p,
```

To fix this issue, a new Highway option `HWY_DISABLE_ATTR` has been
introduced in Highway to explicitly disable compiler target attributes,
as we rely on a source-based CPU dispatcher. Therefore, this patch
updates to the latest Highway main.  This patch also extends the native
CI ppc64 build to include Clang, and sets testing against Python 3.12.