Improve invalid slice error messages in 1.11
Thanks to c87c7a612ee7f9, invalid slices in 1.11 have started raising
exceptions like (example from the scikit-learn test suite):

```
  File ".../sklearn/feature_selection/univariate_selection.py", line 407, in _get_support_mask
    kept_ties = ties[:max_feats - mask.sum()]
IndexError: invalid index
```

This makes the minimal changes so the error message becomes:

```
  File ".../sklearn/feature_selection/univariate_selection.py", line 407, in _get_support_mask
    kept_ties = ties[:max_feats - mask.sum()]
IndexError: failed to coerce slice entry of type numpy.float64 to integer
```

For master we should just dike out all this custom coercion logic and
replace it with a call to `PySlice_GetIndicesEx`, but that changes
exception types and other stuff that I don't want to risk during the
beta period, so this is a minimal fix submitted against 1.11
directly (!!).