DOC: fix a small np.einsum example
[skip azp]

"..." is required if `a` is multi-dimensional, e.g.:
a = np.arange(25).reshape(5,5)

Otherwise, this error is raised:
ValueError: operand has more dimensions than subscripts given in
einstein sum, but no '...' ellipsis provided to broadcast the extra
dimensions.