Fix inclusion of both math.h and cmath causing missing symbols
Error was:

  npy_math.h:257:28: error: 'signbit' was not declared in this scope; did you mean 'std::signbit'?
    257 |     #define npy_signbit(x) signbit((x))
        |                            ^~~~~~~