BUG: lib: Fix error raised by insert.
When `insert` is given a single out-of-bounds index in a
list, e.g.

    np.insert([0, 1, 2], [99], [3, 4])  # 99 is out of bounds

a TypeError was being raised because of a bug in the formatting
of the message.

Before this change, the error is

    TypeError: %i format: a number is required, not list

After, we get the expected

    IndexError: index [99] is out of bounds for axis 0 with size 3