BUG: Fix datetime->string conversion
size_t was being cast to char, causing bizarre errors like

    RuntimeError: The string provided for NumPy ISO datetime formatting was too short, with length 2000

Fixes #9712