MAINT: Avoid exception in NpzFile destructor if constructor raises BadZipFile (#15604)
Previously if you gave an invalid zip file to NpzFile, zipfile_factory would raise BadZipFile and NpzFile.__exit__ would be called, which accessed members which had not yet been set, leading to a confusing second exception like this:

    zipfile.BadZipFile: File is not a zip file
    Exception ignored in: <function NpzFile.__del__ at 0x9b8ef0>
    Traceback (most recent call last):
      File "numpy/lib/npyio.py", line 230, in __del__
        self.close()
      File "numpy/lib/npyio.py", line 221, in close
        if self.zip is not None:
    AttributeError: 'NpzFile' object has no attribute 'zip'

This change makes __exit__ safe even when __init__ did not complete.