BUG: fix distutils/cpuinfo.py:getoutput()
If getstatusoutput() throws an exception, getoutput() tries to catch it,
but then crashes with:

  UnboundLocalError: local variable 'output' referenced before assignment

because it tries to return the non-existent result of getstatusoutput().