BUG: Fix format statement associated with AttributeError.
Before this fix, a reference such as `numpy.wxyz` produced an
incorrect error message because of the invalid format specifiers
in the error message string:

    >>> import numpy
    >>> numpy.wxyz
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/.../numpy/__init__.py", line 206, in __getattr__
        "module %s has no attribute $s".format(__name__, attr))
    AttributeError: module %s has no attribute $s

After the fix:

    >>> import numpy
    >>> numpy.wxyz
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/.../numpy/__init__.py", line 206, in __getattr__
        "{!r}".format(__name__, attr))
    AttributeError: module 'numpy' has no attribute 'wxyz'